### ISSUE TITLE
When mixing headlines and plain lists bullet points use wrong indentation

### ISSUE THREAD

**Issue by hstock** [yashi/org-textile#1]
Hi, I was expecting I could use plain lists as sub-items of headlines and export parts of the headlines as bullet points using the H: export option. (See below for an example)
I have fixed this in 233efe7dfc3418f297421da224e422db2c7c01b9. 

Let me know whether you would accept this change in functionality and I will gladly add a test case, too.

Org Mode sample content:

```
* First Headline
:PROPERTIES:
:EXPORT_OPTIONS: H:0
:END:
** Second Headline
*** Third Headline
- Item A
- Item B
```

Expected textile output:
```
h1. First Headline
* Second Headline
** Third Headline
*** Item A
*** Item B
```

Actual output:
```
h1. First Headline
* Second Headline
** Third Headline
* Item A
* Item B
```

**Comment by yashi** [comment]
It looks good to me.  I'll accept a pr with test cases.  Thank you!

**Comment by hstock** [comment]
Just added pull request #2 fixing this issue.

**Comment by yashi** [comment]
Thank you for your PR!  I just add some comments there.  I really appreciate your feedback!
