### ISSUE TITLE
[Request] Add to Melpa

### ISSUE THREAD

**Issue by Atlas48** [yashi/org-textile#5]
Hello!

I am interested enough in this package as to see it added to MELPA.

I've made a recipe for you, even.

```elisp
(org-textile :repo "yashi/org-textile" :fetcher github)
```

**Comment by yashi** [comment]
it's already been there since 2014.
https://github.com/melpa/melpa/commit/f222c2e749a5b6f23c553c30b95af78993786ca5

Thank you for asking. :smile:

**Comment by Atlas48** [comment]
🤔

**Comment by yashi** [comment]
https://melpa.org/#/ox-textile

If you have any questions, please reopen this issue.

**Comment by Atlas48** [comment]
just felt like an idiot, that's all...
